# Codecov configuration for BunSQLiteORM
coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/*.d.ts"

flag_management:
  default_rules:
    carryforward: true