name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How would you use this feature? Provide code examples if possible.
      render: typescript
      placeholder: |
        // Example of how the feature would be used
        const user = await User.find().where('age').greaterThan(18);
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: What areas would this feature affect?
      options:
        - label: Query API
        - label: Entity definitions
        - label: Validation
        - label: Migrations
        - label: Performance
        - label: TypeScript types
        - label: Documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with documentation
        - label: I can help with testing